name: Pytest Automated Testing
on: [push]

jobs:
  automated-testing:
    name: Automated Testing
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel pytest
        python setup.py install

    - name: Pytest Test Runner
      run: pytest -v .