name: Pytest Automated Testing
on: [push]

jobs:
  automated-testing:
    name: Automated Testing
    runs-on: ubuntu-latest
    steps:

    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
      
    - name: Setup Poetry
      run: |
        curl -sL https://install.python-poetry.org | python
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        poetry config virtualenvs.in-project true
    
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        poetry install
        poetry run pip install pytest-github-actions-annotate-failures

    - name: Pytest Test Runner
      run: poetry run python -m pytest -p no:sugar