name: YAPF Formatting Check
on:
  pull_request:
  push:
    branches:
      - master


jobs:
  formatting-check:
    name: Automated Formatting
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        architecture: x64
      
    - name: Setup Poetry
      run: |
        curl -sL https://install.python-poetry.org | python
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        poetry config virtualenvs.in-project true
    
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        poetry install

    - name: Yapf Formatter
      run: |
        poetry run yapf --verbose -ir simplematrixbotlib tests examples
    
    - name: Commit Changes
      run: |
        git config --local user.email "no-reply@example.com"
        git config --local user.name "YAPF Formatter"
        git add *
        git commit -m "YAPF Formatter" || echo Formatting not needed
    
    - name: Push Changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN }}
        force: true
