name: YAPF Formatting Check
on:
  pull_request:
  push:
    branches:
      - master


jobs:
  formatting-check:
    name: Automated Formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Yapf Formatter
      run: |
        python -m pip install toml yapf; yapf --verbose -ir .
    
    -name: Commit Changes
      run: |
        git config --local user.email "no-reply@example.com"
        git config --local user.name "YAPF Formatter"
        git add *
        git commit -m "YAPF Formatter"
    
    -name: Push Changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN }}
        force: true
